#!/usr/bin/env bash

if [[ $(realpath .git/hooks) == $(realpath ${0%/*}) ]]; then
	exit 0
fi

if [[ -d .git ]]; then
	if [[ -d .git/hooks ]]; then
		if find .git/hooks -mindepth 1 -not -name "*.sample" | grep -q .; then
			echo "$(realpath $(realpath .git)/hooks) is not empty. Clean it up to succeed."
			exit 2
		fi
		rm -rv .git/hooks
	fi

	if [[ -L .git/hooks ]]; then
		echo "$(realpath .git)/hooks is a link, will not touch it. Clean it up to succeed."
		exit 3
	fi

	if [[ -e .git/hooks ]]; then
		echo "$(realpath .git)/hooks is still there. This is unexpected. Carefully clean it up to succeed."
		exit 4
	fi

	ln -sfnv $(realpath --relative-to .git/ ${0%/*}) .git/hooks
fi
