#!/bin/bash

for file in \
	/usr/share/git/contrib/hooks/setgitperms.perl \
	/usr/share/git-core/contrib/hooks/setgitperms.perl \
	;
do
	[[ -x $file ]] && exec ${file} "$@"
	[[ -f $file ]] && exec perl ${file} "$@"
done
